CREATE TABLE player(
    id SERIAL PRIMARY KEY,
    dicord_id BIGINT UNIQUE NOT NULL,
    minecraft_username VARCHAR(50) UNIQUE NOT NULL
    balance NUMERIC(10, 2) NOT NULL DEFAULT 0
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)